name: markdownlint
on:
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Run markdownlint (non-blocking)
        run: |
          npx --yes markdownlint-cli@0.39.0 "**/*.md" || true
